name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Clone Repo
      uses: actions/checkout@v2
    - name: Build SmartcarMqttController
      run: |
       cd AndroidApp
       ./gradlew build --stacktrace
